config/routes.rb
ProjektR::Application.routes.draw do

  resources :maps

  resources :post_addresses

  resources :contacts

  resources :exhibitor_informations

  mount Ckeditor::Engine => '/ckeditor'

  resources :emails

  controller :for_exhibitors do
    get 'utstallare' => :index
  end
  resources :newsfeeds

  resources :exhibitors

  resources :info_texts

  resources :entry_forms

  resources :categories do
    resources :schedules
    resources :rooms
  end

  root 'exhibition#index', as: 'exhibition'
  controller :admin do
    get 'admin' => :index
    get 'admin_for' => :admin_for_exhibitors
    get 'statistics' => :statistics
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :schedules

  resources :rooms

  get "exhibition/index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exhibitors
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_destroy :ensure_a_contact_remains

  private
  def ensure_a_contact_remains
    if Contact.count.zero?
      raise "Du kan inte ta bort den sista kontakten"
    end
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry_form.rb
class EntryForm < ActiveRecord::Base
end

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  belongs_to :category





  validates :title, :link, :category_id, :position,   presence: true
  validates :title, uniqueness: true
  validates :title, length: { minimum: 2 }


end

app/models/info_text.rb
class InfoText < ActiveRecord::Base
  after_destroy :ensure_a_text_remains

  private
  def ensure_a_text_remains
    if InfoText.count.zero?
      raise "Du kan inte ta bort den sista texten"
    end
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  mount_uploader :image, MapLoaderUploader

  after_destroy :ensure_a_map_remains

  validates :image, allow_blank: true, format: {
      with:     %r{\.(gif|jpeg|jpg|png)}i,
      message:  'must be a URL for GIF, JPG or PNG image.'
  }



  private
  def ensure_a_map_remains
    if Map.count.zero?
      raise "Du kan inte ta bort den sista kartan"
    end
  end

end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
end

app/models/post_address.rb
class PostAddress < ActiveRecord::Base
  after_destroy :ensure_an_address_remains

  private
  def ensure_an_address_remains
    if PostAddress.count.zero?
      raise "Du kan inte ta bort den sista adressen"
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :schedules

  #before_destroy :ensure_not_referenced_by_any_schedules

  private

  #def ensure_not_referenced_by_any_schedules
   # if :schedules.empty?
     # return true
   # else
    #  errors.add(:base, 'Room is refered in schedule')
     # return false
   # end
 # end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/admin_for_exhibitors.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>


<div class="hidden-xs row">
  <div class="col-sm-6 col-sm-offset-3"  id="banner">
    <%= link_to exhibition_path, :class=>'button' do %>
        <%= image_tag('logo.png', :class=> 'logo')%>
    <% end %>
  </div>
</div>



<div class="row exhibitor-info">
  <div class="col-xs-offset-1 col-sm-offset-3 col-xs-10 col-sm-6"><p class="exhibitor-info-header"><%= @info.header %></p></div>
  <div class="col-xs-offset-1 col-sm-offset-3 col-xs-10 col-sm-6"><p class="exhibitor-info-content"><%= sanitize(@info.content) %></p></div>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-3">
    <%= link_to edit_exhibitor_information_path(@info.id) do %>
        <button>Hantera Text</button>
    <% end %>
  </div>
</div>
<div class="row contacts hidden-xs hidden-sm">
  <div class="col-md-4 col-md-offset-3"><p class="contact-header"><%= @contact1.name %></p></div>
  <div class="col-md-4"><p class="contact-header"><%= @contact2.name %></p></div>

  <div class="col-md-offset-3 col-md-4"><p class="contact-telephone"><%= @contact1.telephone_number %></p></div>
  <div class="col-md-3"><p class="contact-telephone"><%= @contact2.telephone_number %></p></div>


  <div class="col-md-offset-3 col-md-4"><p class="contact-mail"><%= @contact1.email %></p></div>
  <div class="col-md-4"><p class="contact-mail"><%= @contact2.email %></p></div>
</div>
<div class="row contacts-sm hidden-md hidden-lg">

  <div class="col-xs-offset-1 col-xs-11 col-sm-9 col-sm-offset-3"><p class="contact-header"><%= @contact1.name %></p></div>
  <div class="col-xs-offset-1 col-xs-10 col-sm-offset-3 col-sm-9"><p class="contact-telephone"><%= @contact1.telephone_number %></p></div>
  <div class="col-xs-offset-1 col-xs-10 col-sm-offset-3 col-sm-9"><p class="contact-mail"><%= @contact1.email %></p></div>


  <div class="col-xs-offset-1 col-xs-11 col-sm-9 col-sm-offset-3"><p class="contact-header"><%= @contact2.name %></p></div>
  <div class="col-xs-offset-1 col-xs-10 col-sm-offset-3 col-sm-9"><p class="contact-telephone"><%= @contact2.telephone_number %></p></div>
  <div class="col-xs-offset-1 col-xs-10 col-sm-offset-3 col-sm-9"><p class="contact-mail"><%= @contact2.email %></p></div>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-3">
    <%= link_to contacts_path do %>
        <button>Hantera Kontakter</button>
    <% end %>
  </div>
</div>

<div class="row contact-address-row">
  <div class="col-md-4 col-sm-offset-3 col-xs-offset-1"><p class="contact-header">Postadress</p></div>
  <div class="col-md-4 col-sm-offset-3 col-xs-offset-1"><p id="text-address"><%= @address.municipality %></p></div>
  <div class="col-md-4 col-sm-offset-3 col-xs-offset-1"><p class="text-address"><%= @address.company %></p></div>
  <div class="col-md-4 col-sm-offset-3 col-xs-offset-1"><p class="text-address"><%= @address.address %></p></div>
  <div class="col-md-4 col-sm-offset-3 col-xs-offset-1"><p class="text-address"><%= @address.post_number_and_city %></p></div>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-3">
    <%= link_to edit_post_address_path(@address) do %>
        <button>Hantera Adress</button>
    <% end %>
  </div>
</div>





<div id="container-end-for-exhibitors" class="row hidden-xs">
</div>

app/views/admin/index.html.erb
<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="hidden-xs row">
  <div class="col-sm-6 col-sm-offset-3"  id="banner">
    <%= link_to exhibition_path, :class=>'button' do %>
        <%= image_tag('logo.png', :class=> 'logo')%>
    <% end %>
  </div>
</div>




<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 infoBox">
    <p class="InfoHeader"><%= @info.title %></p>
    <p class="InfoContentText"><%= sanitize(@info.content) %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <%= link_to  edit_info_text_path(@info.id) do %>
        <button>Redigera text</button>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-xs-4 col-sm-2 col-xs-offset-1 col-sm-offset-3"><p class="NewsHeader">Nyheter</p></div>
</div>
<% @newsfeed.each do |nf| %>
    <div class="row NewsBox">
      <div class="col-xs-5 col-xs-offset-1 col-sm-3 col-sm-offset-3"><p class="NewsTitle"><%= nf.title %></p></div>
      <div class="col-xs-5 col-sm-3 "><p class="NewsTimestamp"><%= nf.created_at.to_s.to(15) %></p></div>
      <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3"><p class="NewsContent"><%= nf.content.truncate(100) %></p></div>
    </div>
    <div class="row">
      <div class="col-xs-offset-3 col-xs-2">
        <%= link_to newsfeed_path(nf.id) do %>
            <button>Läs</button>
        <% end %>
      </div>
      <div class="col-xs-2">
    <%= link_to edit_newsfeed_path(nf.id) do %>
        <button>Redigera</button>
    <% end %>
      </div>
      <div class="col-xs-2">
        <%= link_to newsfeed_path(nf.id), method: :delete, data: { confirm: 'Are you sure?' } do %>
          <button>Ta bort</button>
      <% end %>
      </div>
    </div>
<% end %>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
<%= link_to new_newsfeed_path do %>
    <button>Skriv nyhet</button>
<% end %>
  </div>
</div>
<!--this div contains the Exhibitor Header/signboard and loops out the categorybuttons-->
<div class="row" id="container-exhibitors">
  <div class="col-sm-3 hidden-xs">
    <%= image_tag('avgransare_utstallare.png', :class=>"delimiter") %>
  </div>
  <% @categories.each do |cat| %>
      <%= link_to category_path(cat.id), remote: true, method: :get, :class => 'button' do %>
          <div class="hidden-xs col-sm-2 cat">
            <p class="cat_title"><%= cat.title %></p>
          </div>
      <% end %>
  <% end %>
</div>

<!--This div outputs the exhibitors when a category has been selected-->
<div id="exhibitor-row" class="row">
  <div class="col-sm-8 col-xs-11 col-xs-offset-1 col-sm-offset-3">
    <div class="row">
      <div id="exhibitor_show" class="col-xs-12"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-3">
     <%= link_to categories_path do %>
    <button>Hantera kategorier</button>
    <% end %>
  </div>
  <div class="col-xs-3">
     <%= link_to exhibitors_path do %>
    <button>Hantera Utställare</button>
    <% end %>
  </div>
</div>

<!--this div contains the Schedule Header/signboard and loops out the roombuttons-->
<div id="container-schedules" class="row">
  <div class="col-sm-3 hidden-xs">
    <%= image_tag('avgransare_schema.png', :class=>"delimiter") %>
  </div>

  <!--This loops out the roombuttons for the leisure schedules-->
  <% @rooms.each do |room| %>
      <%= link_to room_path(room.id), remote: true, method: :get, :class => 'button' do %>
          <div class="hidden-xs col-sm-2 room">
            <p class="cat_title"><%= room.title %></p>
          </div>
      <% end %>
  <% end %>
</div>

<!--This div outputs the schedule when a room has been selected-->
<div class="row">
  <div class="col-xs-11 col-xs-offset-1 col-sm-8 col-sm-offset-3">
    <div class="row">
      <div id="schedule_show" class="col-xs-12"></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-offset-3 col-xs-3">
    <%= link_to rooms_path do %>
    <button>Hantera lokaler</button>
    <% end %>

  </div>
  <div class="col-xs-3">
    <%= link_to schedules_path do %>
        <button>hantera schema</button>
    <% end %>
  </div>
</div>

<div id="container-map" class="row">
  <div class="col-sm-3 hidden-xs">
    <%= image_tag('avgransare_karta.png', :class=>"delimiter") %>
  </div>
  <div id="mobilMap" class="col-xs-4 hidden-sm hidden-md hidden-lg">
    <p class="delimiter_title">Karta</p>
  </div>
</div>
<div class="row">
  <div class="col-xs-12col-sm-8 col-sm-offset-3">
    <%= image_tag(@map.image, :class=>"map") %>
  </div>

</div>


<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <%= link_to edit_map_path(@map) do %>
        <button>Redigera karta</button>
    <% end %>
  </div>
</div>




<!--Bottom navbar-->
<div id="container-end" class="row hidden-xs">
  <%= link_to logout_path, method: :delete  do %>
      <div class="col-xs-2  Login_text">
        <p class="Login_text">Logga ut</p>
      </div>
  <% end %>
</div>

app/views/admin/statistics.html.erb
<h1>Välkommen till administrationssidan!</h1>
<%= Time.now%><br>
<%= (@total_newsfeeds) %> Nyheter är inlagda i systemet<br>
<%= (@total_categories) %> Utställar kategorier är inlagda i systemet<br>
<%= (@total_exhibitors) %> Utställare är inlagda i systemet<br>
<%= (@total_rooms) %> Seminarielokaler är inlagda i systemet<br>
<%= (@total_schedules) %> Schemahändelser är inlagda i systemet<br>