config/routes.rb
ProjektR::Application.routes.draw do

  resources :maps

  resources :post_addresses

  resources :contacts

  resources :exhibitor_informations

  mount Ckeditor::Engine => '/ckeditor'

  resources :emails

  controller :for_exhibitors do
    get 'utstallare' => :index
  end
  resources :newsfeeds

  resources :exhibitors

  resources :info_texts

  resources :entry_forms

  resources :categories do
    resources :schedules
    resources :rooms
  end

  root 'exhibition#index', as: 'exhibition'
  controller :admin do
    get 'admin' => :index
    get 'admin_for' => :admin_for_exhibitors
    get 'statistics' => :statistics
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :schedules

  resources :rooms

  get "exhibition/index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exhibitors
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_destroy :ensure_a_contact_remains

  private
  def ensure_a_contact_remains
    if Contact.count.zero?
      raise "Du kan inte ta bort den sista kontakten"
    end
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry_form.rb
class EntryForm < ActiveRecord::Base
end

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  belongs_to :category





  validates :title, :link, :category_id, :position,   presence: true
  validates :title, uniqueness: true
  validates :title, length: { minimum: 2 }


end

app/models/info_text.rb
class InfoText < ActiveRecord::Base
  after_destroy :ensure_a_text_remains

  private
  def ensure_a_text_remains
    if InfoText.count.zero?
      raise "Du kan inte ta bort den sista texten"
    end
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  mount_uploader :image, MapLoaderUploader

  after_destroy :ensure_a_map_remains

  validates :image, allow_blank: true, format: {
      with:     %r{\.(gif|jpeg|jpg|png)}i,
      message:  'must be a URL for GIF, JPG or PNG image.'
  }



  private
  def ensure_a_map_remains
    if Map.count.zero?
      raise "Du kan inte ta bort den sista kartan"
    end
  end

end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
end

app/models/post_address.rb
class PostAddress < ActiveRecord::Base
  after_destroy :ensure_an_address_remains

  private
  def ensure_an_address_remains
    if PostAddress.count.zero?
      raise "Du kan inte ta bort den sista adressen"
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :schedules

  #before_destroy :ensure_not_referenced_by_any_schedules

  private

  #def ensure_not_referenced_by_any_schedules
   # if :schedules.empty?
     # return true
   # else
    #  errors.add(:base, 'Room is refered in schedule')
     # return false
   # end
 # end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]

  # GET /maps
  # GET /maps.json
  def index
    @maps = Map.all
  end

  # GET /maps/1
  # GET /maps/1.json
  def show
  end

  # GET /maps/new
  def new
    @map = Map.new
  end

  # GET /maps/1/edit
  def edit
  end

  # POST /maps
  # POST /maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Karta skapad.' }
        format.json { render action: 'show', status: :created, location: @map }
      else
        format.html { render action: 'new' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maps/1
  # PATCH/PUT /maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Karta uppdaterad' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:image)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/maps/_form.html.erb
<%= form_for(@map) do |f| %>
  <% if @map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@map.errors.count, "error") %> förhindrade kartan från att bli sparad</h2>

      <ul>
      <% @map.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
  <div class="actions">
    <%= f.submit 'Spara' %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Redigera Karta</h1>

<%= render 'form' %>

<%= link_to 'Förhandsgranska', @map %> |
<%= link_to 'Tillbaka', admin_path %>

app/views/maps/index.html.erb
<h1>Listing maps</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.image %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New map</h1>

<%= render 'form' %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Karta</strong>
  <%= image_tag(@map.image) %>
</p>

<%= link_to 'Redigera', edit_map_path(@map) %> |
<%= link_to 'Tillbaka', admin_path %>