config/routes.rb
ProjektR::Application.routes.draw do

  resources :maps

  resources :post_addresses

  resources :contacts

  resources :exhibitor_informations

  mount Ckeditor::Engine => '/ckeditor'

  resources :emails

  controller :for_exhibitors do
    get 'utstallare' => :index
  end
  resources :newsfeeds

  resources :exhibitors

  resources :info_texts

  resources :entry_forms

  resources :categories do
    resources :schedules
    resources :rooms
  end

  root 'exhibition#index', as: 'exhibition'
  controller :admin do
    get 'admin' => :index
    get 'admin_for' => :admin_for_exhibitors
    get 'statistics' => :statistics
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :schedules

  resources :rooms

  get "exhibition/index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exhibitors
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_destroy :ensure_a_contact_remains

  private
  def ensure_a_contact_remains
    if Contact.count.zero?
      raise "Du kan inte ta bort den sista kontakten"
    end
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry_form.rb
class EntryForm < ActiveRecord::Base
end

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  belongs_to :category





  validates :title, :link, :category_id, :position,   presence: true
  validates :title, uniqueness: true
  validates :title, length: { minimum: 2 }


end

app/models/info_text.rb
class InfoText < ActiveRecord::Base
  after_destroy :ensure_a_text_remains

  private
  def ensure_a_text_remains
    if InfoText.count.zero?
      raise "Du kan inte ta bort den sista texten"
    end
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  mount_uploader :image, MapLoaderUploader

  after_destroy :ensure_a_map_remains

  validates :image, allow_blank: true, format: {
      with:     %r{\.(gif|jpeg|jpg|png)}i,
      message:  'must be a URL for GIF, JPG or PNG image.'
  }



  private
  def ensure_a_map_remains
    if Map.count.zero?
      raise "Du kan inte ta bort den sista kartan"
    end
  end

end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
end

app/models/post_address.rb
class PostAddress < ActiveRecord::Base
  after_destroy :ensure_an_address_remains

  private
  def ensure_an_address_remains
    if PostAddress.count.zero?
      raise "Du kan inte ta bort den sista adressen"
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :schedules

  #before_destroy :ensure_not_referenced_by_any_schedules

  private

  #def ensure_not_referenced_by_any_schedules
   # if :schedules.empty?
     # return true
   # else
    #  errors.add(:base, 'Room is refered in schedule')
     # return false
   # end
 # end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/exhibition_controller.rb
class ExhibitionController < ApplicationController
  skip_before_action :authorize

  def index
    @rooms = Room.order(:title)
    @testRoom = Room.find(3)
    @categories = Category.order(:id)
    @info = InfoText.order(:id).last
    @stefan = @categories.select(:id)
    @exhibitors = Exhibitor.order(:title)
    @schedules = Schedule.order(:time)
    @cat = Category.find_by(params[:id])
    @newsfeed = Newsfeed.order(:created_at).limit(3).reverse_order
    @mapArray = Map.all.order(:id).reverse
    @map = @mapArray.first
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/exhibition_helper.rb
module ExhibitionHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exhibition/index.html.erb
<div class="row">
  <div id="upphit" class="hidden-xs col-sm-3 col-sm-offset-9">
    <%= link_to utstallare_path, :class=>'button' do %>
        <%= image_tag('menu_forutstallare.png', :class=> "exhibitorButton") %>
    <% end %>

  </div>
</div>
<div class="hidden-xs row">
  <div class="col-sm-6 col-sm-offset-3"  id="banner">
    <%= link_to exhibition_path, :class=>'button' do %>
        <%= image_tag('logo.png', :class=> 'logo')%>
    <% end %>
  </div>
</div>

<div class="hidden-sm hidden-md hidden-lg row navbar-fixed-top">
  <%= link_to exhibition_path, :class=>'dropdown-toggle', :data => {:toggle=>"dropdown", :target=>"#admin_menu"} do %>
      <div class="col-xs-2 dropdown" id="admin_menu">
        <%= image_tag('meny_dropdown.png', :class=> 'dropdownmenu')%>
        <ul class="dropdown-menu">
          <div id="dropdownscroll" class="row">
            <div class="col-xs-offset-2 col-xs-10">
              <a href="#container-start"><p class="visitText">Start</p></a>
              <a href="#container-exhibitors"><p class="visitText">Utställare</p></a>
              <a href="#container-schedules"><p class="visitText">Schema</p></a>
              <a href="#container-map"><p class="visitText">Karta</p></a>
            </div>
          </div>
        </ul>
  <% end %>
  </div>

  <div class="col-xs-10">
    <%= link_to exhibition_path, :class=>'button' do %>
        <%= image_tag('logga_framtidsmassan.png', :class=> 'logo')%>
    <% end %>
  </div>
</div>


<div class="row" id="container-start">
  <div class="hidden-xs col-sm-12" id="side">
    <div class="row" id="menu_links">
      <div class="col-xs-2 col-xs-offset-2"><a href="#container-start"><p class="menu_links">Start</p></a></div>
      <div class="col-xs-2"><a href="#container-exhibitors"><p class="menu_links">Utställare</p></a></div>
      <div class="col-xs-2"><a href="#container-schedules"><p class="menu_links">Schema</p></a></div>
      <div class="col-xs-2"><a href="#container-map"><p class="menu_links">Karta</p></a></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3 infoBox">
    <p class="InfoHeader"><%= @info.title %></p>
    <p class="InfoContentText"><%= sanitize(@info.content) %></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-4 col-sm-2 col-xs-offset-1 col-sm-offset-3"><p class="NewsHeader">Nyheter</p></div>



</div>
<% @newsfeed.each do |nf| %>
<div class="row NewsBox">

  <div class="col-xs-5 col-xs-offset-1 col-sm-3 col-sm-offset-3"><p class="NewsTitle"><%= nf.title %></p></div>
  <div class="col-xs-5 col-sm-3 "><p class="NewsTimestamp"><%= nf.created_at.to_s.to(15) %></p></div>
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-3"><p class="NewsContent"><%= nf.content %></p></div>

</div>

<% end %>
<div class="row">

</div>
<div class="row" id="container-exhibitors">
  <div class="col-sm-3 hidden-xs">
    <%= image_tag('avgransare_utstallare.png', :class=>"delimiter") %>
  </div>
  <div id="mobilExhibitor" class="col-xs-4 hidden-sm hidden-md hidden-lg">
    <!--<%= image_tag('avgransare_utstallare_mobil.png', :class=>"delimiter2") %>-->
    <p class="delimiter_title">Utställare</p>
  </div>
  <% @categories.each do |cat| %>
    <%= link_to category_path(cat.id), remote: true, method: :get, :class => 'button' do %>
      <div class="hidden-xs col-sm-2 cat">
        <p class="cat_title"><%= cat.title %></p>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row catXs">
<% @categories.each do |cat| %>
    <%= link_to category_path(cat.id), remote: true, method: :get, :class => 'button' do %>
        <div class="col-xs-4 hidden-sm hidden-md hidden-lg cat">
          <p class="cat_title"><%= cat.title %></p>
        </div>
    <% end %>
<% end %>
</div>

<div id="exhibitor-row" class="row">
  <div class="col-sm-8 col-xs-11 col-xs-offset-1 col-sm-offset-3">
    <div class="row">
      <div id="exhibitor_show" class="col-xs-12"></div>
    </div>
  </div>
</div>

<div id="container-schedules" class="row">
  <div id="mobilSchema" class="col-xs-4 hidden-sm hidden-md hidden-lg">
   <!-- <%= image_tag('avgransare_schema_mobil.png', :class=>"delimiter2") %> -->
    <p class="delimiter_title">Schema</p>
  </div>
  <div class="col-sm-3 hidden-xs">
    <%= image_tag('avgransare_schema.png', :class=>"delimiter") %>
  </div>

  <% @rooms.each do |room| %>
    <%= link_to room_path(room.id), remote: true, method: :get, :class => 'button' do %>
      <div class="hidden-xs col-sm-2 room">
        <p class="cat_title"><%= room.title %></p>
      </div>
    <% end %>
  <% end %>
</div>

<div class="row catXs">
  <% @rooms.each do |room| %>
      <%= link_to room_path(room.id), remote: true, method: :get, :class => 'button' do %>
          <div class="col-xs-4 hidden-sm hidden-md hidden-lg col-sm-2 room">
            <p class="cat_title"><%= room.title %></p>
          </div>
      <% end %>
  <% end %>
</div>

<div class="row">
  <div class="col-xs-11 col-xs-offset-1 col-sm-8 col-sm-offset-3">
    <div class="row">
      <div id="schedule_show" class="col-xs-12 schedule_show"></div>
    </div>
  </div>
</div>

<div id="container-map" class="row">
  <div class="col-sm-3 hidden-xs">
    <%= image_tag('avgransare_karta.png', :class=>"delimiter") %>
  </div>
  <div id="mobilMap" class="col-xs-4 hidden-sm hidden-md hidden-lg">
    <p class="delimiter_title">Karta</p>
  </div>
</div>
<div class="row">
  <div class="col-xs-12col-sm-8 col-sm-offset-3">
    <%= image_tag("Karta_1600px_52p_senaste.png", :class=>"map") %>
  </div>

</div>


<div id="container-end" class="row hidden-xs">
  <%= link_to login_path, method: :new do %>
    <div class="col-xs-2  Login_text">
      <p class="Login_text">Logga in</p>
      </div>
      <% end %>

  <%= link_to  "https://twitter.com/Framtidsmassan" do %>
      <div class="col-xs-1 col-xs-offset-7 social_button">
        <%= image_tag('twitter_ikon.png', :class=> 'socialButtonImage') %>
      </div>
  <% end %>

  <%= link_to "http://instagram.com/framtidsmassan" do %>
      <div class="col-xs-1 social_button">
        <%= image_tag('instagram_button.png', :class=> 'socialButtonImage') %>
      </div>
  <% end %>
  <%= link_to  "https://www.facebook.com/pages/Framtidsm%C3%A4ssan-Karlshamn/611075925630143" do %>
      <div class="col-xs-1 social_button">
        <%= image_tag('facebook_button.png', :class=> 'socialButtonImage') %>
      </div>
  <% end %>
</div>

<div id="container-end-xs" class="row hidden-sm hidden-md hidden-lg">





        <div id="upphit" class="col-xs-4">
          <%= link_to utstallare_path, :class=>'button' do %>
          <%= image_tag('forutstallare_knapp.png', :class=>'forutstallareKnappXs' ) %>
          <% end %>
        </div>
  <%= link_to  "https://twitter.com/Framtidsmassan" do %>
      <div id="twitter" class="col-xs-1 col-xs-offset-4 social_button">
        <%= image_tag('twitter_ikon.png', :class=> 'socialButtonImage') %>
      </div>
  <% end %>
  <%= link_to "http://instagram.com/framtidsmassan" do %>
      <div id="instagram" class="col-xs-1 social_button">
        <%= image_tag('instagram_button.png', :class=> 'socialButtonImage') %>
      </div>
  <% end %>
  <%= link_to  "https://www.facebook.com/pages/Framtidsm%C3%A4ssan-Karlshamn/611075925630143" do %>
      <div id="facebook" class="col-xs-1  social_button">
        <%= image_tag('facebook_button.png', :class=> 'socialButtonImage') %>
      </div>
  <% end %>
</div>

<div class="row UpAgain">
  <%= link_to  "#container-start", :class=> 'social_button' do %>
      <div href="#upphit" id="UpAgainDiv" class="col-sm-1 col-sm-offset-10 hidden-xs UpAgain navbar-fixed-bottom">
      </div>
  <% end %>
</div>