config/routes.rb
ProjektR::Application.routes.draw do

  resources :maps

  resources :post_addresses

  resources :contacts

  resources :exhibitor_informations

  mount Ckeditor::Engine => '/ckeditor'

  resources :emails

  controller :for_exhibitors do
    get 'utstallare' => :index
  end
  resources :newsfeeds

  resources :exhibitors

  resources :info_texts

  resources :entry_forms

  resources :categories do
    resources :schedules
    resources :rooms
  end

  root 'exhibition#index', as: 'exhibition'
  controller :admin do
    get 'admin' => :index
    get 'admin_for' => :admin_for_exhibitors
    get 'statistics' => :statistics
  end

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get "sessions/create"
  get "sessions/destroy"

  resources :users

  resources :schedules

  resources :rooms

  get "exhibition/index"

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :exhibitors
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  after_destroy :ensure_a_contact_remains

  private
  def ensure_a_contact_remains
    if Contact.count.zero?
      raise "Du kan inte ta bort den sista kontakten"
    end
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/entry_form.rb
class EntryForm < ActiveRecord::Base
end

app/models/exhibitor.rb
class Exhibitor < ActiveRecord::Base
  belongs_to :category





  validates :title, :link, :category_id, :position,   presence: true
  validates :title, uniqueness: true
  validates :title, length: { minimum: 2 }


end

app/models/info_text.rb
class InfoText < ActiveRecord::Base
  after_destroy :ensure_a_text_remains

  private
  def ensure_a_text_remains
    if InfoText.count.zero?
      raise "Du kan inte ta bort den sista texten"
    end
  end
end

app/models/map.rb
class Map < ActiveRecord::Base
  mount_uploader :image, MapLoaderUploader

  after_destroy :ensure_a_map_remains

  validates :image, allow_blank: true, format: {
      with:     %r{\.(gif|jpeg|jpg|png)}i,
      message:  'must be a URL for GIF, JPG or PNG image.'
  }



  private
  def ensure_a_map_remains
    if Map.count.zero?
      raise "Du kan inte ta bort den sista kartan"
    end
  end

end

app/models/newsfeed.rb
class Newsfeed < ActiveRecord::Base
end

app/models/post_address.rb
class PostAddress < ActiveRecord::Base
  after_destroy :ensure_an_address_remains

  private
  def ensure_an_address_remains
    if PostAddress.count.zero?
      raise "Du kan inte ta bort den sista adressen"
    end
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  has_many :schedules

  #before_destroy :ensure_not_referenced_by_any_schedules

  private

  #def ensure_not_referenced_by_any_schedules
   # if :schedules.empty?
     # return true
   # else
    #  errors.add(:base, 'Room is refered in schedule')
     # return false
   # end
 # end
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  skip_before_action :authorize, only: [:show]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.find(params[:id])
    @exhibitors = Exhibitor.order(:title)
    @schedules = Schedule.all
    @rooms = Room.all
    @events = Array.new
    @eventExhibitor = Array.new

  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    @testarRoom = Room.find(2)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Kategori skapad' }
        format.js
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Kategori uppdaterad' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/newsfeeds_helper.rb
module NewsfeedsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div class="row">
  <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"><p class="Exhibitor_Header">Namn</p></div>
  <div class="col-xs-offset-6 col-lg-2 col-md-2 col-sm-2 col-xs-2 "><p class="Exhibitor_Header">Plats</p></div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <br>
      </div>
      <div id="modal_body" class="modal-body schedule_show">
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>

<div class="row">
  <% @exhibitors.each do |ex| %>
    <% if ex.category_id == category.id%>
      <div id="catbox" class="col-xs-8 ">
        <p id="ScheduleTextMargin" class="ExhibitorTitle"><%= ex.title %></p>
        <div class="row">
          <div class="col-sm-2 col-xs-2"><%= image_tag('besok_pil.png') %></div>
          <div class="col-sm-10 col-xs-10">
            <%= link_to ex.link do %>
              <p class="visitText">Besök</p>
            <% end %>
          </div>
        </div>
        <% @schedules.each do |s| %>
          <% if ex.id == s.exhibitors_id%>
            <% @events.push(s.rooms_id) %>
            <% @eventExhibitor.push(ex) %>
          <% end %>
        <% end %>
        <% if @rooms.exists?(:id => @events.last ) and @schedules.exists?(:exhibitors_id => ex.id) %>
          <div class="row kalle">
            <div class="col-sm-2 col-xs-2 arrow-box"><%= image_tag('blapil.png', :class=>"pil" ) %></div>
            <div class="col-sm-10 col-xs-10 seminarie-box">
              <!-- Button trigger modal
              Har inte lyckats med att skicka med ett rum id!!-->
              <p><%= link_to 'Seminarietid', room_path(@events.last), remote: true, method: :get, :class => 'visitText2', :data=>{:toggle=>"modal", :target=>"#myModal"}%></p>
            </div>
          </div>
        <% end %>
      </div>
      <div class="col-xs-2">
        <p class="ExhibitorPosition"><%= ex.position %></p>
      </div>
    <% end %>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> förhindrade kategorin från att bli sparad</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit 'Spara' %>
  </div>
<% end %>

app/views/categories/_room.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= @room.title %>
  </div>
</div>

<div class="row">

  <div class="col-xs-3"><p class="ScheduleHeader">Utställare</p></div>
  <div class="col-xs-2 col-xs-offset-4 col-sm-2 "><p class="ScheduleHeader">Tid</p></div>


</div>
<div class="row">
  <% @schedules.each do |s| %>

      <% if s.rooms_id == @room.id%>

          <% @exhibitors.each do |ex| %>
              <% if s.exhibitors_id == ex.id%>
                  <div class="col-xs-7" id="catbox" ><p id="ScheduleTextMargin" class="ExhibitorTitle"><%= ex.title %></p></div>
              <% end %>
          <% end %>


          <div class="col-xs-5"><p id="ScheduleTextMargin" class="ScheduleTime"><%= s.time %></p></div>





      <% end %>
  <% end %>
</div>

app/views/categories/create.js.erb
$('#exhibitor_show').html("<%= escape_javascript render(@category) %>");

app/views/categories/edit.html.erb
<h1>Redigera kategori</h1>

<%= render 'form' %>

<%= link_to 'Visa', @category %> |
<%= link_to 'Tillbaka', categories_path %>

app/views/categories/index.html.erb
<h1>Kategorier</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Titel</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Visa', category %></td>
        <td><%= link_to 'Redigera', edit_category_path(category) %></td>
        <td><%= link_to 'Ta bort', category, method: :delete, data: { confirm: 'Vill du ta bort denna kategori?' } %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Skapa kategori', new_category_path %>

app/views/categories/new.html.erb
<h1>Skapa en ny kategori</h1>
<p>Bra att veta: Innan du kan lägga till en utställare så behöver du skapa den kategori som utställaren ska tillhöra</p>

<%= render 'form' %>

<%= link_to 'Tillbaka', admin_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>


    <div class="row exhibitorRow">

      <div class="col-xs-1"></div>

      <div id=""class="col-xs-10">
        <div class=" row entry">

          <div class="col-xs-12 entry cat">

            <h3 class="cat_title"><%= @categories.title %></h3>

            <% @exhibitors.each do |ex| %>
                <% if ex.category_id == @categories.id%>
                    <div class=" row">


                      <div class="col-xs-9"><h1><%= ex.title %></h1>
                        </div>

                    </div>
                <% end %>
            <% end %>

          </div>


        </div>

      </div>

      <div class="col-xs-1"></div>
    </div>


<%= link_to 'Redigera', edit_category_path(@category) %> |
<%= link_to 'Tillbaka', admin_path %>

app/views/categories/show.js.erb
//$('#exhibitor_show').slideToggle("fast");

//$('#exhibitor_show').slideToggle("fast", function(){
//$(this).parent().unbind();

$('#exhibitor_show').html("<%= escape_javascript render(@category) %>");

app/views/categories/showRooms.js.erb
$('#myModal').html("<%= escape_javascript render(@room) %>");